config/routes.rb
Rails.application.routes.draw do
  resources :trips do
    resources :stops
  end
  root :to => "trips#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :stops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def show
    @trip = Trip.find(params[:trip_id])

    @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    @client.account.messages.create(
      from: ENV['TWILIO_NUMBER'],
      to: '+1'+ @trip.phone_number,
      body: 'Here is your final destination.' + ' https://goo.gl/maps/CKMxSZwhoQG2'
      # media_url: "https://goo.gl/maps/CKMxSZwhoQG2"
    )
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  # def index
  #   @trips = Trip.all
  # end

  # GET /trips/1
  # GET /trips/1.json
  def show

  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  # def edit
  # end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    # p @trip
    # @exist_number = Trip.find_by(phone_number: @trip.phone_number)
    # p "_____"
    # p @exist_number
    # if @exist_number
      # redirect_to action: 'new'
      # render :new
      # render action: "new"
    # else
      respond_to do |format|
        if @trip.save
          format.html { redirect_to @trip, notice: 'Your trip is registered!' }
          format.json { render :show, status: :created, location: @trip }

          @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
          @client.account.messages.create(
            from: ENV['TWILIO_NUMBER'],
            to: '+1'+ @trip.phone_number,
            body: 'Welcome to MARTA.'
          )
        else
          format.html { render :new }
          format.json { render json: @trip.errors, status: :unprocessable_entity }
        end
      end
    # end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  # def update
  #   respond_to do |format|
  #     if @trip.update(trip_params)
  #       format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @trip }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @trip.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /trips/1
  # DELETE /trips/1.json
  # def destroy
  #   @trip.destroy
  #   respond_to do |format|
  #     format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      if Trip.exists?(params[:id]) == true
        @trip = Trip.find(params[:id])
      else
        @trip = Trip.new
        render action: "new"
        # @trip.save
        # @trip = Trip.find(params[:id])
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QrSms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	  <meta charset="utf-8">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="title">
		    <h1>Welcome to MARTA Connect</h1>
	  </div>

	  <div class="instructions">
		    <p>Input your phone number for up to date directions and more...
	  </div>
    <%= yield %>

    <div class="service-container">
      <h2>Service Alerts</h2>
      <span> No service advisories at this time</span>
    </div>


    <div class="footer">
      For more information, visit <a href="http://www.itsmarta.com">www.itsmarta.com</a>
      <p>
          Some legal copy here
      <p>
      <%= image_tag 'brand.png' %>

    </div>
  </body>
</html>

app/views/stops/show.html.erb
<%= @message %>

app/views/trips/_form.html.erb
<%= form_for(trip) do |f| %>

<div class="phonesubmission">
  <div class="field">
    <%= f.text_field :phone_number, placeholder: "Enter Phone Number" %>
  </div>

  <!-- <div class="actions" name="Send"> -->

  <div>
    <%= f.submit 'SUBMIT'%><br>
    <!-- <div class="clearbtn">
    <%= link_to 'Clear Phone Number', new_trip_path %>
    </div> -->
  </div>


</div>

  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.phone_number %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<%= render 'form', trip: @trip %>

app/views/trips/show.html.erb
<div class="phonesubmission">
  <div class="form-textbox">
    <p id="notice"><%= notice %></p>
      <p>
        <strong>Phone number:</strong>
        <%= @trip.phone_number %>
      </p>
  </div>

  <div class="clearbtn">
    <%= link_to 'Re-enter your number', new_trip_path %>
  </div>
</div>